//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSStudios.TomScript.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDSStudios.TomScript.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START_PROGRAM=initialise
        ///END_PROGRAM=terminate
        ///CREATE=fabricate
        ///VARIABLE=changeable
        ///WRITE=inscribe
        ///USER_INPUT=the input value
        ///SET=alter
        ///CALCULATE=enumerate
        ///REPEAT=recurse
        ///FOREVER=perpetually
        ///TIMES=repetitions
        ///WHILE=while
        ///REPEAT_END=cease
        ///|=and
        ///RESULT=product
        ///IF=presuming that
        ///IF_ELSE_IF=unless not but that
        ///IF_ELSE=unless not
        ///IF_END=conclude
        ///IS_EQUAL_TO=is equal to
        ///IS_NOT_EQUAL_TO=is not equal to
        ///IS_GREATER_THAN=is greater than
        ///IS_GREATER_THAN_OR_EQUAL_TO=is greater than or equal to
        ///IS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fancy {
            get {
                return ResourceManager.GetString("fancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START_PROGRAM=début
        ///END_PROGRAM=fin
        ///CREATE=créer
        ///VARIABLE=une variable
        ///WRITE=écrire
        ///USER_INPUT=entrée utilisateur
        ///SET=définir
        ///CALCULATE=calculer
        ///REPEAT=répéter
        ///FOREVER=pour toujours
        ///TIMES=fois
        ///WHILE=tandis que
        ///REPEAT_END=arrêtez
        ///|=et
        ///RESULT=résultat
        ///IF=si
        ///IF_ELSE_IF=sinon si
        ///IF_ELSE=autre
        ///IF_END=terminé
        ///IS_EQUAL_TO=est égal à
        ///IS_NOT_EQUAL_TO=n&apos;est pas égal à
        ///IS_GREATER_THAN=est supérieur à
        ///IS_GREATER_THAN_OR_EQUAL_TO=est supérieur ou égal à
        ///IS_LESS_THAN=est inférieur à
        ///IS_LESS_THAN_O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string francais {
            get {
                return ResourceManager.GetString("francais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START_PROGRAM=compiler please start here
        ///END_PROGRAM=compiler please end here
        ///CREATE=id like to create
        ///VARIABLE=a variable called
        ///WRITE=please write
        ///USER_INPUT=the text inputted by the user
        ///SET=id like to set
        ///CALCULATE=please can you calculate
        ///REPEAT=i would like to to repeat the following code
        ///FOREVER=forever
        ///TIMES=times
        ///WHILE=while
        ///REPEAT_END=and thats it thanks
        ///|=and also
        ///RESULT=the result of the previous calculation
        ///IF=please decide whether
        ///IF_ELSE_IF=unless its not but
        ///IF_ELSE=unless i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string friendly {
            get {
                return ResourceManager.GetString("friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START_PROGRAM=start
        ///END_PROGRAM=end
        ///CREATE=create
        ///VARIABLE=variable
        ///WRITE=write
        ///USER_INPUT=user input
        ///SET=set
        ///CALCULATE=calculate
        ///REPEAT=repeat
        ///FOREVER=forever
        ///TIMES=times
        ///WHILE=while
        ///REPEAT_END=stop
        ///|=and
        ///RESULT=result
        ///IF=if
        ///IF_ELSE_IF=elseif
        ///IF_ELSE=else
        ///IF_END=done
        ///IS_EQUAL_TO=is equal to
        ///IS_NOT_EQUAL_TO=is not equal to
        ///IS_GREATER_THAN=is greater than
        ///IS_GREATER_THAN_OR_EQUAL_TO=is greater than or equal to
        ///IS_LESS_THAN=is less than
        ///IS_LESS_THAN_OR_EQUAL_TO=is less than or equal to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string standard {
            get {
                return ResourceManager.GetString("standard", resourceCulture);
            }
        }
    }
}
